[[headers]]
for = "/*"
[headers.values]
Content-Type = "text/html; charset=UTF-8"

[[headers]]
for = "/src/*.tsx"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/src/*.ts"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/src/*.js"
[headers.values]
Content-Type = "application/javascript"
